[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
nom = "7.1"
tap = "1.0.1"
